management.endpoint.health.show-details: always
management.health.binders.enabled: true
management.endpoints.web.exposure.include: bindings, health, metrics
spring.cloud.stream:
 instanceCount: 1
 bindings:
   validationinput:
     destination: raw
     group: t1
     consumer:
       configuration:
         max:
           poll:
             records: 100
       concurrency: 6
   validationoutput:
     destination: valid