spring.cloud.stream:
 instanceCount: 1
 bindings:
  input:
    destination: raw
    group: t1
    consumer:
      configuration:
        max:
          poll:
            records: 100
      concurrency: 6
  output:
    destination: valid